const mongoose = require('mongoose');

const flashcardSchema = new mongoose.Schema({
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  chatId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Chat',
  },
  topic: {
    type: String,
    required: true,
  },
  category: {
    type: String,
    default: 'General'
  },
  sourceDocument: {
    type: String, // Can store document title or ID if applicable
  },
  cards: [{
    front: String,
    back: String,
    isBookmarked: { type: Boolean, default: false },
    status: { type: String, enum: ['new', 'learning', 'mastered'], default: 'new' },
    nextReviewDate: { type: Date, default: Date.now }
  }],
  generatedContent: {
    type: String,
    description: 'The raw fallback content generated by the AI'
  }
}, { timestamps: true });

module.exports = mongoose.model('Flashcard', flashcardSchema);
